### ISSUE TITLE
本の詳細が見れる

### ISSUE THREAD

**Issue by rick1919** [rick1919/libtech#3]
・本の概要が見れる
・本を読んだ人の要約ベース（初期は自分のみ）
・興味を持った本を購入希望=≻Amazon
3pt=>10pt

**Comment by rick1919** [comment]
https://docs.google.com/presentation/d/1VOTByjwJJfWFnDi8KcC6Wnjrj2l7H2fZztPi52aL2os/edit#slide=id.g3312d91b65_0_64
2pt

**Comment by rick1919** [comment]
- [x] 2pt 本の詳細ページでは運営側が要約した簡単な内容、外部サイトの詳細からの引用をみれるようにする
- [x] 1pt 詳細ページにAmazonリンクを貼る(今回は5つのみなのでベタでやる)
- [x] 1pt Amazonリンクをタップすると別タブで購入ページを開く
- [x] 6pt 本をDBから引っ張ってこれるようにする（調査も含む）

**Comment by rick1919** [comment]
次回からDB設定に移ります。

**Comment by rick1919** [comment]
DBについて調べたサイト
・https://techacademy.jp/magazine/7151
・https://stackoverflow.com/questions/20364256/rake-commands-not-recognized
・https://qiita.com/kieaiaarh/items/11d1c935f232995d1a06
等その他いくつかで調べた
mysqlを利用しようと思い調査したがそもそも勘違いで、railsに備わっているsqliteで十分であるとわかった

マイグレーション機能がまだ曖昧にしか理解できていない
またテスト機能の導入タイミングはいつにすべきかわからない＜＝チュートリアルを見本にやっていこうと思う
方針は大まかではあるが、SQLiteを利用し作成していく

**Comment by nagatashinya** [comment]
> sqliteで十分

何に対して十分かがわからないので補足お願いします。

**Comment by rick1919** [comment]
DBについて調べたサイト
・https://techacademy.jp/magazine/7151
・https://stackoverflow.com/questions/20364256/rake-commands-not-recognized
・https://qiita.com/kieaiaarh/items/11d1c935f232995d1a06
等その他いくつかで調べた
mysqlを利用しようと思い調査したがそもそも勘違いで、開発環境においてはrailsに備わっているsqliteで対応できることがわかった
デプロイ時にherokuを利用するため、herokuにpushする際にpostgresqlを使いたいと思う
https://qiita.com/_naonosuke/items/e4cdf3b8178e976c8e67

マイグレーション機能がまだ曖昧にしか理解できていない
またテスト機能の導入タイミングはいつにすべきかわからない＜＝チュートリアルを見本にやっていこうと思う
方針は大まかではあるが、今回開発環境ではSQLiteを利用し作成していく

**Comment by nagatashinya** [comment]
設計方針もお願いします。

**Comment by rick1919** [comment]
設計方針
カラム
-name =タイトル
-summary =サマリー
-author =著者
の三つで考えています。
上２つは誤って、変数名と異なるカラム名を与えてしましました。
３つ目のauthorはまだ作成していないので２つが完成次第作成します。

**Comment by rick1919** [comment]
設計方針
カラム
- name =タイトル
- summary =サマリー
- author =著者
の三つで考えています。
上２つは誤って、変数名と異なるカラム名を与えてしましました。
３つ目のauthorはまだ作成していないので２つが完成次第作成します。

**Comment by rick1919** [comment]
明日表示させるところをゴール
質問事項が自分の中であるような気がするので、まとめておきます。

**Comment by rick1919** [comment]
DBからはparams[:id]で引っ張って来ればいいのか？
表示するものはカラムごとに別々で引っ張ってきた方がいいのか？
今思いつくのは以上です。
