### ISSUE TITLE
本の一覧が見れる

### ISSUE THREAD

**Issue by rick1919** [rick1919/libtech#5]
・本の書名とサマリの一覧が見れる

**Comment by rick1919** [comment]
https://docs.google.com/presentation/d/1VOTByjwJJfWFnDi8KcC6Wnjrj2l7H2fZztPi52aL2os/edit#slide=id.p
3pt

**Comment by rick1919** [comment]
一ページに3冊
今回は5冊をデータとして扱う

**Comment by nagatashinya** [comment]
> 一ページに3冊
今回は5冊をデータとして扱う

残り2冊はどうやったら閲覧できる？
全部で5冊なら1ページに表示でいいのでは？
5冊で目的が達成できる？5冊でやりたいなら分野絞るとか必要なんじゃないかな。

**Comment by rick1919** [comment]
今回はあまり重厚なサマリを盛り込まない方向で考えます。
1ページ表示でやれるようにします
あ、スクロールも1ページ内で行っているんでしたね！
1ページ表記ということをはき違えてました。
今回ビジネス書のみで作成します。
きっかけを与える目的は果たせると思うので。

**Comment by rick1919** [comment]
- [x] 本のタイトル、著者名、サマリのまとまりを作る
- [x] まとまりを5つ一画面で表示できるようにする
- [x] まとまりの中のタイトルをタップすると詳細ページに飛ぶ
- [x] bootstraを利用する
- [x] サンプルとして最初にベタで5つまとまりを表示する
- [x] custom.css.scss(bootstrap_and_overrides.css)内でスマホ向けに調整する

**Comment by nagatashinya** [comment]
* スタイルを当てるとかデザインの調整のタスクが全く入ってないけど大丈夫？
* まとまりを5つ表示する方法はベタで5つ並べるのと、ループを5回する方法があるので、後者のつもりならいいですが、そうでないならそれぞれタスクを分けてください。
* まとまりをクリックして遷移するのは少し難しいので、タイトルリンクをクリックすると遷移するというのとタスクを分けてください
* スマホ前提のイメージで書いていないと思うので常に意識してください(クリック→タップとか)

**Comment by nagatashinya** [comment]
> まとまりをタップすると本の詳細ページに飛ぶ
まとまりの中のタイトルをタップすると詳細ページに飛ぶ

順番逆。

**Comment by nagatashinya** [comment]
> スタイルを当てる（ワイヤーを参考に）

どうやって？

**Comment by rick1919** [comment]
custom.scssを使ってやろうかと考えています。

**Comment by nagatashinya** [comment]
> custom.scssを使ってやろうかと考えています。

それじゃわからない。
Bootstrapをベースにスタイルの微調整をcustom.css.scss内でやろうと思います。
というような説明がほしいです。

**Comment by rick1919** [comment]
boostrapの存在を今思い出しました。
スマホにも適応しやすいということなのでそうします。

**Comment by rick1919** [comment]
<meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=10.0, user-scalable=yes">
viweportを使うことによって簡易的に表示面ではスマホに適応するレスポンシブデザインにした。
